[build]
  publish = ".next"
  command = "npm install --include=dev && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_ENV = "production"
  NEXT_PUBLIC_ENV = "production"
  NEXT_PUBLIC_DEBUG_MODE = "false"
  NEXT_PUBLIC_SHOW_MOCK_DATA = "false"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"